<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>Sf2.Remake.Reference</RootNamespace>
    <AssemblyName>Sf2.Remake.Reference</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\Sf2.Remake.Domain\Sf2.Remake.Domain.csproj" />
  </ItemGroup>
</Project>
